### ISSUE TITLE
Compilion aborts

### ISSUE THREAD

**Issue by ErikKalkoken** [ZerkerEOD/heimdall-listener#1]
I tried to install the listener, but it complains about a missing file. Do I maybe need to install some additional packages?

This is on Ubuntu 22.04.5 with go 1.23.1.

```sh
go install github.com/ZerkerEOD/heimdall-listener/cmd/heimdall-listener@latest
go: downloading github.com/ZerkerEOD/heimdall-listener v0.0.0-20241020180718-29a2997b95c8
go: downloading github.com/google/gopacket v1.1.19
go: downloading github.com/go-text/typesetting v0.1.0
# github.com/google/gopacket/pcap
go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.
```

**Comment by ZerkerEOD** [comment]
@ErikKalkoken, I'll test compiling on Ubuntu today and will get back to you.

**Comment by ZerkerEOD** [comment]
@ErikKalkoken, for the gopacket/pcap, it appears that it relies on the libpcap-dev on the Unix side. You should be able to install it with the following command:

`apt install libpcap-dev`

https://github.com/google/gopacket/issues/280#issuecomment-410738534

I will leave this open for a little bit unless you let me know this fixes it for you.

**Comment by ErikKalkoken** [comment]
Sorry for the belated reply. Can confirm this fix works. 
You may want to add this to your installation instructions.
